name: Terraform Security group Pipeline - 002

on:
  workflow_dispatch:
    inputs:
      TERRAFORM_ACTION:
        description: "terraform security creation ? OR deletion ?"
        required: true
        type: choice
        options:
          - creation
          - deletion

env:
  AWS_REGION: 'us-east-1'
  WORKING_DIR: '02-securitygroups' # Defined common directory here

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: AWS-devlopment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 'Configure AWS credentials'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -reconfigure
        working-directory: ${{ env.WORKING_DIR }}

      # ---------------------------------------------------
      # Terraform Plan (Context aware)
      # ---------------------------------------------------
      - name: Terraform Plan
        run: |
          if [ "${{ github.event.inputs.TERRAFORM_ACTION }}" == "deletion" ]; then
            terraform plan -destroy
          else
            terraform plan
          fi
        working-directory: ${{ env.WORKING_DIR }}

      # ---------------------------------------------------
      # Terraform Apply (only when action is 'creation')
      # ---------------------------------------------------
      - name: Terraform Apply
        if: github.event.inputs.TERRAFORM_ACTION == 'creation'
        run: terraform apply -auto-approve
        working-directory: ${{ env.WORKING_DIR }}

      # ---------------------------------------------------
      # Terraform Destroy (only when action is 'deletion')
      # ---------------------------------------------------
      - name: Terraform Destroy
        if: github.event.inputs.TERRAFORM_ACTION == 'deletion'
        run: terraform destroy -auto-approve
        working-directory: ${{ env.WORKING_DIR }}